### ISSUE TITLE
Passing multiple context in a single workflow

### ISSUE THREAD

**Issue by kirand1303** [jramoyo/flowee#1]
Hi,

Can we pass multiple context in a single workflow comprising multiple tasks? In the current design each workflow shares only single context across tasks. How do you perform cleanUp of workflow if it is required in few cases?

Thanks

**Comment by jramoyo** [comment]
Hi, can you provide a bit more background on your use case?

`WorkflowContext` is backed by a general purpose `ConcurrentMap<String, Object>`, so you can store pretty much any object -- including other instances of a `WorkflowContext`.

Alternatively, you can also extend `WorkflowContext` to support the data that you need.

Hope this helps!

**Comment by kirand1303** [comment]
Thank you very much. This helps !
